apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-deploy

images:
  - name: image-name
    newName: quay.io/abdul_ali/actions-test:dev

commonLabels:
  group: kustomize
  app: demo

resources:
  - ../../../../base/base-go?ref=master

patchesStrategicMerge:
  - ./patches/configmap.yaml
  - ./patches/deployment.yaml

patchesJson6902:

######### config maps #########
- target:
    version: v1
    kind: ConfigMap
    name: service
  patch: |-
    - op: replace
      path: /metadata/name
      value: github-actions-dev

######### deployment ######### 
- target:
    group: apps
    version: v1
    kind: Deployment
    name: deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: github-actions-dev
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: github-actions-dev
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - configMapRef: { name: github-actions-dev }
    - op: remove
      path: /spec/template/spec/containers/0/livenessProbe


######### service ######### 
- target:
    version: v1
    kind: Service
    name: service
  patch: |-
    - op: replace
      path: /metadata/name
      value: github-actions-dev
    - op: replace
      path: /spec/selector/app
      value: github-actions-dev   

